---
- name: Deploy ServiceAccount
  local_action:
    module:  k8s
    state: "{{ calico_kube_resources_state }}"
    kubeconfig: "{{ calico_kube_resources_kubeconfig }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: calico-node
        namespace: kube-system

- name: Deploy Custom resource definitions
  local_action:
    module:  k8s
    state: "{{ calico_kube_resources_state }}"
    kubeconfig: "{{ calico_kube_resources_kubeconfig }}"
    definition:
      apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
         name: "{{ item.plural }}.crd.projectcalico.org"
      spec:
        scope: "{{ item.scope | default('Cluster') }}"
        group: crd.projectcalico.org
        version: v1
        names:
          kind: "{{ item.kind }}"
          plural: "{{ item.plural }}"
          singular: "{{ item.singular }}"
  with_items:
    - kind: FelixConfiguration
      singular: felixconfiguration
      plural: felixconfigurations
    - kind: BGPPeer
      singular: bgppeer
      plural: bgppeers
    - kind: BGPConfiguration
      singular: bgpconfiguration
      plural: bgpconfigurations
    - kind: IPPool
      singular: ippool
      plural: ippools
    - kind: HostEndpoint
      singular: hostendpoint
      plural: hostendpoints
    - kind: ClusterInformation
      singular: clusterinformation
      plural: clusterinformations
    - kind: GlobalNetworkPolicy
      singular: globalnetworkpolicy
      plural: globalnetworkpolicies
    - kind: GlobalNetworkSet
      singular: globalnetworkset
      plural: globalnetworksets
    - kind: NetworkPolicy
      singular: networkpolicy
      plural: networkpolicies
      scope: Namespaced
    - kind: IPAMBlock
      plural: ipamblocks
      singular: ipamblock
    - kind: BlockAffinity
      plural: blockaffinities
      singular: blockaffinity
    - kind: IPAMHandle
      plural: ipamhandles
      singular: ipamhandle
    - kind: IPAMConfig
      plural: ipamconfigs
      singular: ipamconfig
    - kind: NetworkSet
      plural: networksets
      singular: networkset

- name: Deploy Cluster role
  local_action:
    module:  k8s
    state: "{{ calico_kube_resources_state }}"
    kubeconfig: "{{ calico_kube_resources_kubeconfig }}"
    definition:
      kind: ClusterRole
      apiVersion: rbac.authorization.k8s.io/v1beta1
      metadata:
        name: calico-node
      rules:
        # The CNI plugin needs to get pods, nodes, and namespaces.
        - apiGroups: [""]
          resources:
            - pods
            - nodes
            - namespaces
          verbs:
            - get
        - apiGroups: [""]
          resources:
            - endpoints
            - services
          verbs:
            # Used to discover service IPs for advertisement.
            - watch
            - list
            # Used to discover Typhas.
            - get
        - apiGroups: [""]
          resources:
            - nodes/status
          verbs:
            # Needed for clearing NodeNetworkUnavailable flag.
            - patch
            # Calico stores some configuration information in node annotations.
            - update
        # Watch for changes to Kubernetes NetworkPolicies.
        - apiGroups: ["networking.k8s.io"]
          resources:
            - networkpolicies
          verbs:
            - watch
            - list
        # Used by Calico for policy information.
        - apiGroups: [""]
          resources:
            - pods
            - namespaces
            - serviceaccounts
          verbs:
            - list
            - watch
        # The CNI plugin patches pods/status.
        - apiGroups: [""]
          resources:
            - pods/status
          verbs:
            - patch
        # Calico monitors various CRDs for config.
        - apiGroups: ["crd.projectcalico.org"]
          resources:
            - globalfelixconfigs
            - felixconfigurations
            - bgppeers
            - globalbgpconfigs
            - bgpconfigurations
            - ippools
            - ipamblocks
            - globalnetworkpolicies
            - globalnetworksets
            - networkpolicies
            - networksets
            - clusterinformations
            - hostendpoints
          verbs:
            - get
            - list
            - watch
        # Calico must create and update some CRDs on startup.
        - apiGroups: ["crd.projectcalico.org"]
          resources:
            - ippools
            - felixconfigurations
            - clusterinformations
          verbs:
            - create
            - update
        # Calico stores some configuration information on the node.
        - apiGroups: [""]
          resources:
            - nodes
          verbs:
            - get
            - list
            - watch
        # These permissions are only requried for upgrade from v2.6, and can
        # be removed after upgrade or on fresh installations.
        - apiGroups: ["crd.projectcalico.org"]
          resources:
            - bgpconfigurations
            - bgppeers
          verbs:
            - create
            - update
        - apiGroups: ["crd.projectcalico.org"]
          resources:
            - blockaffinities
            - ipamblocks
            - ipamhandles
          verbs:
            - get
            - list
            - create
            - update
            - delete
        - apiGroups: ["crd.projectcalico.org"]
          resources:
            - ipamconfigs
          verbs:
            - get
        # Block affinities must also be watchable by confd for route aggregation.
        - apiGroups: ["crd.projectcalico.org"]
          resources:
            - blockaffinities
          verbs:
            - watch

- name: Deploy Cluster Role Binding
  local_action:
    module:  k8s
    state: "{{ calico_kube_resources_state }}"
    kubeconfig: "{{ calico_kube_resources_kubeconfig }}"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1beta1
      kind: ClusterRoleBinding
      metadata:
        name: calico-node
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: calico-node
      subjects:
      - kind: ServiceAccount
        name: calico-node
        namespace: kube-system
      - kind: User
        name: calico-node
        namespace: kube-system

- name: Deploy Typha service
  local_action:
    module: k8s
    state: "{{ calico_kube_resources_state }}"
    kubeconfig: "{{ calico_kube_resources_kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: calico-typha
        namespace: kube-system
        labels:
          k8s-app: calico-typha
      spec:
        type: ClusterIP
        ports:
          - port: 5473
            protocol: TCP
            targetPort: 5473
            name: calico-typha

- name: Create K8S Master node dummy objects
  local_action:
    module: k8s
    state: "{{ calico_kube_resources_state }}"
    kubeconfig: "{{ calico_kube_resources_kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        labels:
          beta.kubernetes.io/arch: amd64
          beta.kubernetes.io/os: linux
          kubernetes.io/arch: amd64
          kubernetes.io/hostname: "{{ item }}"
          kubernetes.io/os: linux
        name: "{{ item }}"
      spec:
        podCIDR: "{{ calico_kube_resources_master_dummy_subnet }}"
  with_items: "{{ groups[kubernetes_ansible_master_group] }}"

- name: Deploy Typha service endpoints
  local_action:
    module: k8s
    state: "{{ calico_kube_resources_state }}"
    kubeconfig: "{{ calico_kube_resources_kubeconfig }}"
    definition: "{{ lookup('template', 'typha-service-endpoints.yml.j2') }}"

- name: Add each router as BGP endpoint
  local_action:
    module: k8s
    state: "{{ calico_kube_resources_state }}"
    kubeconfig: "{{ calico_kube_resources_kubeconfig }}"
    definition:
      kind: BGPPeer
      metadata:
        name: "{{ hostvars[item]['ansible_fqdn'] }}"
      spec:
        peerIP: "{{ hostvars[item][hostvars[item]['calico_kube_resources_router_interface']]['ipv4']['address'] }}"
        asNumber: "{{ kubernetes_autonomous_system_number }}"
  with_items: "{{ groups[kubernetes_ansible_router_group] }}"

- name: Add default BGP configuration
  local_action:
    module: k8s
    state: "{{ calico_kube_resources_state }}"
    kubeconfig: "{{ calico_kube_resources_kubeconfig }}"
    definition:
      kind: BGPConfiguration
      metadata:
        name: default
      spec:
        nodeToNodeMeshEnabled: false
        asNumber: "{{ kubernetes_autonomous_system_number }}"
